# -*- coding: utf-8 -*-
"""Finance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11C6OgNDbNi6XcpAWkvrJj9gDOAX11bas
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,roc_curve,classification_report
import seaborn as sns
# %matplotlib inline
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

"""### Problem statement -  Loan prediction

## Step 1 : Data Gathering
"""

df = pd.read_csv("Finance.csv")

df

"""##  Step 2:EDA - Read and explore the data"""

df.info()

df.describe()

df.isna().sum()*100/len(df)

"""## Step 3: Missing value imputation

### 1.Gender
"""

sns.countplot(x = df['Gender'])

df['Gender'].mode()[0]

df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

"""### 2.Married"""

sns.countplot(x= df['Married'])

df['Married'].mode()[0]

df['Married'] = df['Married'].fillna(df['Married'].mode()[0])

"""### 3.Dependents"""

sns.countplot(x=df['Dependents'])

df['Dependents'].value_counts()

df['Dependents'].mode()[0]

df['Dependents'] = df['Dependents'].fillna(df['Dependents'].mode()[0])

"""### 4.Self_Employed"""

sns.countplot(x = df['Self_Employed'])

df['Self_Employed'].mode()[0]

df['Self_Employed'] = df['Self_Employed'].fillna(df['Self_Employed'].mode()[0])

df.isna().sum()*100/len(df)

"""### 5.LoanAmount"""

df['LoanAmount'].median()

df['LoanAmount'] = df['LoanAmount'].fillna(df['LoanAmount'].median())

"""### 6.Loan_Amount_Term"""

df['Loan_Amount_Term'].median()

df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].median())

"""### 7.Credit_History"""

sns.countplot(x = df['Credit_History'])

df['Credit_History'].mode()[0]

df['Credit_History'] = df['Credit_History'].fillna(df['Credit_History'].mode()[0])

df.isna().sum()

"""## Step 4 : Feature creation"""

df.head()

df.replace({
    "Loan_Status": {'N': 0, 'Y': 1},
    "Gender": {'Male': 0, 'Female': 1},
    "Education": {'Not Graduate': 0, 'Graduate': 1},
    "Married": {'No': 0, 'Yes': 1},
    "Self_Employed": {'No': 0, 'Yes': 1}
}, inplace=True)

df

"""## Step 5 : Train Test split the data"""

def train_test_split_and_features(df):
    y = df["Loan_Status"]
    x = df.drop(['Loan_Status', 'Loan_ID'], axis=1)
    x = pd.get_dummies(data = x, columns = ["Property_Area","Dependents"])
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state = 0)
    print(x.head(5))
    print(x.columns)
    features = list(x.columns)
    return x_train, x_test, y_train, y_test,features

x_train, x_test, y_train, y_test,features = train_test_split_and_features(df)

"""## Step 6: Fit and evaluate model"""

def fit_and_evaluate_model(x_train, x_test, y_train, y_test):
    random_forest =  RandomForestClassifier(random_state=0,\
                                            max_depth=5,\
                                            min_samples_split= 0.01,\
                                            max_features= 0.8,
                                            max_samples= 0.8)

    model = random_forest.fit(x_train, y_train)
    random_forest_predict = random_forest.predict(x_test)
    random_forest_conf_matrix = confusion_matrix(y_test, random_forest_predict)
    random_forest_acc_score = accuracy_score(y_test, random_forest_predict)
    print("confussion matrix")
    print(random_forest_conf_matrix)
    print("\n")
    print("Accuracy of Random Forest:",random_forest_acc_score*100,'\n')
    print(classification_report(y_test,random_forest_predict))
    return model

model = fit_and_evaluate_model(x_train, x_test, y_train, y_test)

importances = pd.DataFrame(model.feature_importances_)
importances['features'] = features
importances.columns = ['importance','feature']
importances.sort_values(by = 'importance', ascending= True,inplace=True)



"""# Step 7: Feature importance"""

import matplotlib.pyplot as plt
plt.barh(importances.feature, importances.importance)



# Predicted Probability for each class

rf_proba = model.predict_proba(x_test)
rf_predict = model.predict(x_test)
print(rf_proba[0:10])
print(rf_predict)